name: 获取Telegram订阅
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
    watch:
      types: started
    repository_dispatch:
      types: get_v2ray
jobs:
  get_link:
    runs-on: ubuntu-latest
    steps:
      - name: '设置python环境'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 设置githup信息
        env:
          email: ${{ secrets.EMAIL }}
          username: ${{ secrets.USERNAME }}
        run: |
          git config --global user.name "$username"
          git config --global user.email "$email"
      - name: 设置SSH私钥信息
        env:
          token_Private_Keys: ${{ secrets.token_Private_Keys }}
        run: |
          mkdir -p ~/.ssh/
          echo "$token_Private_Keys" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
      - name: 获取订阅链接
        run: |
          git clone https://github.com/ronghuaxueleng/get_chat.git get_chat
          git clone git@github.com:ronghuaxueleng/telegram-session.git session
          cp -rf session/+8615901254680.session get_chat/
          cp -rf session/default.conf get_chat/
          cd get_chat
          pip install -r requirements.txt
          python get_link.py
      - name: 删除过多的workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.AUTH_PAT }}
          repository: ${{ github.repository }}
          retain_days: 1